### ISSUE TITLE
Data opening problem

### ISSUE THREAD

**Issue by Rosheim** [moykeen/supermjo-doc#1]
Hi, 
I've tried to update to the supermjograph because the usual mjograph was no longer able to print TeX on my graphs, but the program supermjograph cannot open any file and quits unexpectedly when asked to import a data file... since it is its primary use, I'm worried I'm no longer going to be able to use it (willing to pay for a working version as nothing comparable exists!).

**Comment by moykeen** [comment]
Thank you for reporting a problem.

I've tested several standard CSV files, and confirmed all of them were loaded correctly.
Can you upload your data file that causes a crash?

Also, what OS version do you use?
I developed the software on Sierra. There can be glitches on the older versions.

**Comment by Rosheim** [comment]
I am using High Sierra and was using Sierra until yesterday (update done in the hope
to fix the problem!). For whatever CSV file I try to input, it quits immediately and replies
in the log the following:

fatal error: separator character is invalid: file /Users/makoto/Documents/mx2/SuperMjograph/SuperMjograph/PlotLayerDataIO.swift, line 93

Note that I have no clue as to how it figured such a file, nowhere to be found on my machine!

**Comment by moykeen** [comment]
Thanks, I figured out what causes the error.
Supermjograph guesses a separator character for CSV based on the default currency grouping separator of your language setting.
If it is neither comma nor period, the program terminates with the fatal error.

In the next release (which will come shortly), I am going to fix this issue to be able to work in any language setting.

**Comment by moykeen** [comment]
Just now I released version 0.8 in which this problem has been solved.

**Comment by Rosheim** [comment]
Hi,

many thanks, that’s very helpful. Just to make sure it’s
not my system that has a problem, I mention that the
new version crashed instantaneously with the following
error message:

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Library/Frameworks/YAML.framework/Versions/A/YAML
  Referenced from: /Applications/SuperMjograph.app/Contents/MacOS/SuperMjograph
  Reason: image not found

Binary Images:
       0x10095d000 -        0x100a80ff7 +com.mjo.SuperMjograph (0.8 - 1) <423BCAAD-5341-30B7-AE15-2AAC9EEB37FC> /Applications/SuperMjograph.app/Contents/MacOS/SuperMjograph
       0x1065bd000 -        0x10660798f  dyld (519.2.1) <CD85EFBA-B9D6-3FD5-B777-A23B2DDEF192> /usr/lib/dyld
    0x7fff428d3000 -     0x7fff428e1ffb  com.apple.opengl (16.2.1 - 16.2.1) <66266ABC-2655-337C-AC64-955A16A8FCBB> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL

Best regards,

P. Peter.


Begin forwarded message:

**Comment by moykeen** [comment]
Oops, it seems linking fails.
I released version 0.8.1 to fix this error.

Thanks

**Comment by Rosheim** [comment]
Hi again,

it works perfectly now, many thanks, you’ve
done a spectacular job, really helping the entire
research community.

Best wishes,

P. Peter.

**Comment by Rosheim** [comment]
Hi, I'm sorry to bother you again with that, it seems the "SuperMjograph" quit unexpectedly error is back! I'm using version 0.15.2 and Mojave, do you know of any problem with such a configuration?

Best regards,

P. Peter.

**Comment by moykeen** [comment]
I daily use SuperMjograph on the same configuration, and it works stably.
Can you tell in what situation the unexpectedly error takes place?
